// Generated by scripts/gen-db-types.mjs from supabase/migrations. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      build_jobs: {
        Row: {
          claim_expires_at: string | null
          claim_token_hash: string | null
          created_at: string
          created_by: string | null
          error: string | null
          id: string
          record: Json
          run_id: string | null
          status: Database["public"]["Enums"]["build_status"]
          store_id: string | null
          updated_at: string
        }
        Insert: {
          claim_expires_at?: string | null
          claim_token_hash?: string | null
          created_at?: string
          created_by?: string | null
          error?: string | null
          id: string
          record: Json
          run_id?: string | null
          status?: Database["public"]["Enums"]["build_status"]
          store_id?: string | null
          updated_at?: string
        }
        Update: {
          claim_expires_at?: string | null
          claim_token_hash?: string | null
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: string
          record?: Json
          run_id?: string | null
          status?: Database["public"]["Enums"]["build_status"]
          store_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "build_jobs_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          description: string
          id: string
          image_url: string | null
          name: string
          position: number
          slug: string
          store_id: string
        }
        Insert: {
          created_at?: string
          description?: string
          id?: string
          image_url?: string | null
          name: string
          position?: number
          slug: string
          store_id: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          image_url?: string | null
          name?: string
          position?: number
          slug?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      collection_products: {
        Row: {
          collection_id: string
          position: number
          product_id: string
          store_id: string
        }
        Insert: {
          collection_id: string
          position?: number
          product_id: string
          store_id: string
        }
        Update: {
          collection_id?: string
          position?: number
          product_id?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "collection_products_collection_id_store_id_fkey"
            columns: ["collection_id", "store_id"]
            isOneToOne: false
            referencedRelation: "collections"
            referencedColumns: ["id", "store_id"]
          },
          {
            foreignKeyName: "collection_products_product_id_store_id_fkey"
            columns: ["product_id", "store_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id", "store_id"]
          },
        ]
      }
      collections: {
        Row: {
          created_at: string
          description: string
          id: string
          image_url: string | null
          name: string
          position: number
          slug: string
          store_id: string
        }
        Insert: {
          created_at?: string
          description?: string
          id?: string
          image_url?: string | null
          name: string
          position?: number
          slug: string
          store_id: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          image_url?: string | null
          name?: string
          position?: number
          slug?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "collections_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_movements: {
        Row: {
          actor_id: string | null
          created_at: string
          delta: number
          id: number
          note: string | null
          qty_after: number
          reason: Database["public"]["Enums"]["inventory_reason"]
          ref: string | null
          store_id: string
          variant_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          delta: number
          id?: never
          note?: string | null
          qty_after: number
          reason: Database["public"]["Enums"]["inventory_reason"]
          ref?: string | null
          store_id: string
          variant_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          delta?: number
          id?: never
          note?: string | null
          qty_after?: number
          reason?: Database["public"]["Enums"]["inventory_reason"]
          ref?: string | null
          store_id?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_movements_variant_id_store_id_fkey"
            columns: ["variant_id", "store_id"]
            isOneToOne: false
            referencedRelation: "product_variants"
            referencedColumns: ["id", "store_id"]
          },
        ]
      }
      nexova_lines: {
        Row: {
          at: string
          id: number
          line: string
          name: string
        }
        Insert: {
          at?: string
          id?: number
          line: string
          name: string
        }
        Update: {
          at?: string
          id?: number
          line?: string
          name?: string
        }
        Relationships: []
      }
      nexova_records: {
        Row: {
          collection: string
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          collection: string
          key: string
          updated_at?: string
          value: Json
        }
        Update: {
          collection?: string
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      product_categories: {
        Row: {
          category_id: string
          position: number
          product_id: string
          store_id: string
        }
        Insert: {
          category_id: string
          position?: number
          product_id: string
          store_id: string
        }
        Update: {
          category_id?: string
          position?: number
          product_id?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_categories_category_id_store_id_fkey"
            columns: ["category_id", "store_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id", "store_id"]
          },
          {
            foreignKeyName: "product_categories_product_id_store_id_fkey"
            columns: ["product_id", "store_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id", "store_id"]
          },
        ]
      }
      product_images: {
        Row: {
          alt: string
          created_at: string
          height: number | null
          id: string
          position: number
          product_id: string
          source_url: string | null
          storage_path: string | null
          store_id: string
          url: string
          width: number | null
        }
        Insert: {
          alt?: string
          created_at?: string
          height?: number | null
          id?: string
          position?: number
          product_id: string
          source_url?: string | null
          storage_path?: string | null
          store_id: string
          url: string
          width?: number | null
        }
        Update: {
          alt?: string
          created_at?: string
          height?: number | null
          id?: string
          position?: number
          product_id?: string
          source_url?: string | null
          storage_path?: string | null
          store_id?: string
          url?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_store_id_fkey"
            columns: ["product_id", "store_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id", "store_id"]
          },
        ]
      }
      product_options: {
        Row: {
          id: string
          name: string
          position: number
          product_id: string
          store_id: string
          values: string[]
        }
        Insert: {
          id?: string
          name: string
          position?: number
          product_id: string
          store_id: string
          values?: string[]
        }
        Update: {
          id?: string
          name?: string
          position?: number
          product_id?: string
          store_id?: string
          values?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "product_options_product_id_store_id_fkey"
            columns: ["product_id", "store_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id", "store_id"]
          },
        ]
      }
      product_variants: {
        Row: {
          allow_backorder: boolean
          compare_at_cents: number | null
          created_at: string
          id: string
          image_id: string | null
          low_stock_threshold: number | null
          options: Json
          position: number
          price_cents: number
          product_id: string
          sku: string | null
          stock_qty: number
          store_id: string
          title: string
          track_stock: boolean
          updated_at: string
          weight_g: number | null
        }
        Insert: {
          allow_backorder?: boolean
          compare_at_cents?: number | null
          created_at?: string
          id?: string
          image_id?: string | null
          low_stock_threshold?: number | null
          options?: Json
          position?: number
          price_cents: number
          product_id: string
          sku?: string | null
          stock_qty?: number
          store_id: string
          title?: string
          track_stock?: boolean
          updated_at?: string
          weight_g?: number | null
        }
        Update: {
          allow_backorder?: boolean
          compare_at_cents?: number | null
          created_at?: string
          id?: string
          image_id?: string | null
          low_stock_threshold?: number | null
          options?: Json
          position?: number
          price_cents?: number
          product_id?: string
          sku?: string | null
          stock_qty?: number
          store_id?: string
          title?: string
          track_stock?: boolean
          updated_at?: string
          weight_g?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_variants_image_id_fkey"
            columns: ["image_id"]
            isOneToOne: false
            referencedRelation: "product_images"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_variants_product_id_store_id_fkey"
            columns: ["product_id", "store_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id", "store_id"]
          },
        ]
      }
      products: {
        Row: {
          attributes: Json
          created_at: string
          description: string
          featured: boolean
          id: string
          locked_fields: string[]
          position: number
          rating_average: number | null
          rating_count: number | null
          seo: Json
          short_description: string
          slug: string
          sold_count: number | null
          source_external_id: string | null
          source_platform: string | null
          source_url: string | null
          status: Database["public"]["Enums"]["product_status"]
          store_id: string
          tags: string[]
          title: string
          updated_at: string
        }
        Insert: {
          attributes?: Json
          created_at?: string
          description?: string
          featured?: boolean
          id?: string
          locked_fields?: string[]
          position?: number
          rating_average?: number | null
          rating_count?: number | null
          seo?: Json
          short_description?: string
          slug: string
          sold_count?: number | null
          source_external_id?: string | null
          source_platform?: string | null
          source_url?: string | null
          status?: Database["public"]["Enums"]["product_status"]
          store_id: string
          tags?: string[]
          title: string
          updated_at?: string
        }
        Update: {
          attributes?: Json
          created_at?: string
          description?: string
          featured?: boolean
          id?: string
          locked_fields?: string[]
          position?: number
          rating_average?: number | null
          rating_count?: number | null
          seo?: Json
          short_description?: string
          slug?: string
          sold_count?: number | null
          source_external_id?: string | null
          source_platform?: string | null
          source_url?: string | null
          status?: Database["public"]["Enums"]["product_status"]
          store_id?: string
          tags?: string[]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          id: string
          phone: string | null
          platform_role: Database["public"]["Enums"]["platform_role"]
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          phone?: string | null
          platform_role?: Database["public"]["Enums"]["platform_role"]
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          phone?: string | null
          platform_role?: Database["public"]["Enums"]["platform_role"]
          updated_at?: string
        }
        Relationships: []
      }
      store_domains: {
        Row: {
          created_at: string
          hostname: string
          id: string
          is_primary: boolean
          kind: Database["public"]["Enums"]["domain_kind"]
          store_id: string
          verified_at: string | null
        }
        Insert: {
          created_at?: string
          hostname: string
          id?: string
          is_primary?: boolean
          kind: Database["public"]["Enums"]["domain_kind"]
          store_id: string
          verified_at?: string | null
        }
        Update: {
          created_at?: string
          hostname?: string
          id?: string
          is_primary?: boolean
          kind?: Database["public"]["Enums"]["domain_kind"]
          store_id?: string
          verified_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "store_domains_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      store_members: {
        Row: {
          created_at: string
          role: Database["public"]["Enums"]["store_role"]
          store_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          role: Database["public"]["Enums"]["store_role"]
          store_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          role?: Database["public"]["Enums"]["store_role"]
          store_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "store_members_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      store_settings: {
        Row: {
          brand: Json
          checkout: Json
          contact: Json
          pages: Json
          policies: Json
          seo: Json
          social: Json
          store_id: string
          template_id: string | null
          theme: Json
          updated_at: string
        }
        Insert: {
          brand?: Json
          checkout?: Json
          contact?: Json
          pages?: Json
          policies?: Json
          seo?: Json
          social?: Json
          store_id: string
          template_id?: string | null
          theme?: Json
          updated_at?: string
        }
        Update: {
          brand?: Json
          checkout?: Json
          contact?: Json
          pages?: Json
          policies?: Json
          seo?: Json
          social?: Json
          store_id?: string
          template_id?: string | null
          theme?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "store_settings_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: true
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      stores: {
        Row: {
          created_at: string
          created_by: string | null
          currency: string
          id: string
          locale: string
          name: string
          slug: string
          status: Database["public"]["Enums"]["store_status"]
          updated_at: string
          verified_at: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          currency?: string
          id?: string
          locale?: string
          name: string
          slug: string
          status?: Database["public"]["Enums"]["store_status"]
          updated_at?: string
          verified_at?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          currency?: string
          id?: string
          locale?: string
          name?: string
          slug?: string
          status?: Database["public"]["Enums"]["store_status"]
          updated_at?: string
          verified_at?: string | null
        }
        Relationships: []
      }
      usage_ledger: {
        Row: {
          cost_usd: number
          created_at: string
          id: number
          job_id: string | null
          meta: Json
          operation: string
          provider: string
          store_id: string | null
          units: number
        }
        Insert: {
          cost_usd?: number
          created_at?: string
          id?: never
          job_id?: string | null
          meta?: Json
          operation: string
          provider: string
          store_id?: string | null
          units?: number
        }
        Update: {
          cost_usd?: number
          created_at?: string
          id?: never
          job_id?: string | null
          meta?: Json
          operation?: string
          provider?: string
          store_id?: string | null
          units?: number
        }
        Relationships: [
          {
            foreignKeyName: "usage_ledger_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "build_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "usage_ledger_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      adjust_stock: {
        Args: {
          p_variant_id: string
          p_delta: number
          p_note?: string
        }
        Returns: number
      }
      create_store: {
        Args: {
          p_name: string
          p_slug: string
        }
        Returns: {
          created_at: string
          created_by: string | null
          currency: string
          id: string
          locale: string
          name: string
          slug: string
          status: Database["public"]["Enums"]["store_status"]
          updated_at: string
          verified_at: string | null
        }
        SetofOptions: {
          from: "*"
          to: "stores"
          isOneToOne: true
          isSetofReturn: false
        }
      }
    }
    Enums: {
      build_status: "queued" | "running" | "done" | "failed" | "cancelled"
      domain_kind: "subdomain" | "custom"
      inventory_reason: "initial" | "manual" | "order" | "cancel" | "sync" | "import"
      platform_role: "user" | "admin"
      product_status: "draft" | "active" | "archived"
      store_role: "staff" | "admin" | "owner"
      store_status: "draft" | "live" | "suspended"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
      build_status: ["queued", "running", "done", "failed", "cancelled"],
      domain_kind: ["subdomain", "custom"],
      inventory_reason: ["initial", "manual", "order", "cancel", "sync", "import"],
      platform_role: ["user", "admin"],
      product_status: ["draft", "active", "archived"],
      store_role: ["staff", "admin", "owner"],
      store_status: ["draft", "live", "suspended"],
    },
  },
} as const
