/**
 * Compose: template + StoreSpec + assets -> a buildable site folder at stores/<slug>/site.
 */
import path from "node:path";
import type { EngineConfig } from "../config.js";
import type { TemplateEntry } from "../schema/manifest.js";
import type { StoreSpec, Theme } from "../schema/store-spec.js";
import { copyDir, ensureDir, exists, linkDir, rmrf, writeJson, writeText } from "../util/fsx.js";
import type { Logger } from "../util/log.js";

export interface ComposeInput {
  spec: StoreSpec;
  template: TemplateEntry;
  config: EngineConfig;
  log: Logger;
  basePath: string;
}

export interface ComposeResult {
  siteDir: string;
  dataFile: string;
  themeFile: string;
  filesCopied: number;
}

export function storeDir(config: EngineConfig, slug: string): string {
  return path.join(config.storesDir, slug);
}

export function siteDirFor(config: EngineConfig, slug: string): string {
  return path.join(storeDir(config, slug), "site");
}

export function assetsDirFor(config: EngineConfig, slug: string): string {
  return path.join(storeDir(config, slug), "assets");
}

const RADIUS: Record<Theme["radius"], string> = { none: "0px", sm: "4px", md: "10px", lg: "18px", full: "999px" };

export function themeCss(theme: Theme, brandName: string): string {
  const families = [...new Set([theme.fonts.heading, theme.fonts.body])].filter(Boolean);
  const importLine = families.length ? `@import url('https://fonts.googleapis.com/css2?${families.map((f) => `family=${encodeURIComponent(f).replace(/%20/g, "+")}:wght@400;500;600;700`).join("&")}&display=swap');` : "";
  return `/* Generated by Nexova for ${brandName}. Edit the StoreSpec, not this file. */
${importLine}
:root {
  --nx-primary: ${theme.colors.primary};
  --nx-secondary: ${theme.colors.secondary};
  --nx-accent: ${theme.colors.accent};
  --nx-bg: ${theme.colors.background};
  --nx-surface: ${theme.colors.surface};
  --nx-text: ${theme.colors.text};
  --nx-muted: ${theme.colors.muted};
  --nx-font-heading: '${theme.fonts.heading}', ui-sans-serif, system-ui, sans-serif;
  --nx-font-body: '${theme.fonts.body}', ui-sans-serif, system-ui, sans-serif;
  --nx-radius: ${RADIUS[theme.radius]};
  --nx-preset: ${theme.preset};
  color-scheme: ${theme.mode};
}
`;
}

export async function composeSite(input: ComposeInput): Promise<ComposeResult> {
  const { spec, template, config, log } = input;
  const siteDir = siteDirFor(config, spec.slug);
  const assetsDir = assetsDirFor(config, spec.slug);

  // Fresh copy of the template (keeps node_modules linked, never copied).
  await rmrf(siteDir);
  await ensureDir(siteDir);
  const filesCopied = await copyDir(template.dir, siteDir, { ignore: ["node_modules", "dist", ".git", ".vite", ".cache", ".DS_Store"] });
  const templateNodeModules = path.join(template.dir, "node_modules");
  if (await exists(templateNodeModules)) {
    try {
      await linkDir(templateNodeModules, path.join(siteDir, "node_modules"));
    } catch (err) {
      log.warn(`could not link node_modules (${err instanceof Error ? err.message : String(err)}); build will install`);
    }
  }

  // Assets -> template public dir
  const publicDir = path.join(siteDir, template.manifest.entry.publicDir, "nexova");
  if (await exists(assetsDir)) {
    await copyDir(assetsDir, publicDir, { ignore: ["index.json"] });
  }

  const dataFile = path.join(siteDir, template.manifest.entry.dataFile);
  const themeFile = path.join(siteDir, template.manifest.entry.themeFile);
  await writeJson(dataFile, spec);
  await writeText(themeFile, themeCss(spec.theme, spec.brand.name));
  await writeJson(path.join(siteDir, "nexova.site.json"), {
    slug: spec.slug,
    templateId: template.manifest.id,
    templateVersion: template.manifest.version,
    basePath: input.basePath,
    engineVersion: config.engineVersion,
    composedAt: new Date().toISOString(),
  });
  log.info(`composed site from template ${template.manifest.id}`, { files: filesCopied, siteDir });
  return { siteDir, dataFile, themeFile, filesCopied };
}
