/**
 * StoreSpec: the canonical data model of Nexova.
 *
 * Everything the engine ingests (TikTok Shop, Instagram, Shopee, Facebook, free text,
 * product lists) is normalized into a StoreSpec. Every template consumes a StoreSpec.
 * This is the single contract between ingestion, enrichment, templates and the CMS.
 *
 * Rules:
 *  - Keep the schema JSON-Schema-friendly (no recursion) because a subset of it is used
 *    for Claude structured outputs (see schema/drafts.ts).
 *  - Never break existing fields; add new optional fields and bump `version`.
 */
import { z } from "zod";

export const STORE_SPEC_VERSION = 1 as const;

export const PlatformSchema = z.enum([
  "tiktok",
  "tiktok_shop",
  "instagram",
  "facebook",
  "shopee",
  "lazada",
  "shopify",
  "website",
  "text",
  "unknown",
]);
export type Platform = z.infer<typeof PlatformSchema>;

export const InventoryStatusSchema = z.enum(["in_stock", "low_stock", "out_of_stock", "preorder", "unknown"]);
export type InventoryStatus = z.infer<typeof InventoryStatusSchema>;

export const ImageSchema = z.object({
  url: z.string().describe("Absolute URL, or a site-relative path once localized (e.g. /nexova/images/p1.jpg)"),
  alt: z.string().default(""),
  width: z.number().int().nullable().default(null),
  height: z.number().int().nullable().default(null),
  sourceUrl: z.string().nullable().default(null).describe("Original remote URL before localization"),
});
export type Image = z.infer<typeof ImageSchema>;

export const MoneySchema = z.object({
  amount: z.number().describe("Numeric price in major units, e.g. 25.9"),
  currency: z.string().describe("ISO 4217 code, e.g. MYR, USD, SGD, IDR, PHP, THB, VND"),
});
export type Money = z.infer<typeof MoneySchema>;

export const InventorySchema = z.object({
  track: z.boolean().default(false),
  quantity: z.number().int().nullable().default(null),
  status: InventoryStatusSchema.default("in_stock"),
});
export type Inventory = z.infer<typeof InventorySchema>;

export const VariantSchema = z.object({
  id: z.string(),
  title: z.string().describe("Human label, e.g. Red / M"),
  options: z.record(z.string(), z.string()).prefault({}).describe("Option name to value, e.g. {Color: Red, Size: M}"),
  price: MoneySchema.nullable().default(null),
  compareAtPrice: MoneySchema.nullable().default(null),
  sku: z.string().nullable().default(null),
  image: ImageSchema.nullable().default(null),
  inventory: InventorySchema.prefault({}),
});
export type Variant = z.infer<typeof VariantSchema>;

export const ProductSourceSchema = z.object({
  platform: PlatformSchema.default("unknown"),
  url: z.string().nullable().default(null),
  externalId: z.string().nullable().default(null),
});

export const ProductSchema = z.object({
  id: z.string().describe("Stable id (slug-like). Generated by the engine."),
  slug: z.string(),
  title: z.string(),
  description: z.string().default("").describe("Full description, plain text or light markdown"),
  shortDescription: z.string().default("").describe("One or two sentences for cards"),
  price: MoneySchema,
  compareAtPrice: MoneySchema.nullable().default(null),
  images: z.array(ImageSchema).default([]),
  options: z.array(z.object({ name: z.string(), values: z.array(z.string()) })).default([]),
  variants: z.array(VariantSchema).default([]),
  inventory: InventorySchema.prefault({}),
  categories: z.array(z.string()).default([]).describe("Category slugs"),
  tags: z.array(z.string()).default([]),
  attributes: z.record(z.string(), z.string()).prefault({}).describe("Free-form specs, e.g. {Material: Cotton}"),
  featured: z.boolean().default(false),
  rating: z.object({ average: z.number(), count: z.number().int() }).nullable().default(null),
  soldCount: z.number().int().nullable().default(null),
  source: ProductSourceSchema.prefault({}),
  confidence: z.number().default(0.5).describe("0..1 how confident the engine is that this is a real, current product"),
  visible: z.boolean().default(true),
});
export type Product = z.infer<typeof ProductSchema>;

export const CategorySchema = z.object({
  slug: z.string(),
  name: z.string(),
  description: z.string().default(""),
  image: ImageSchema.nullable().default(null),
});
export type Category = z.infer<typeof CategorySchema>;

export const CollectionSchema = z.object({
  slug: z.string(),
  name: z.string(),
  description: z.string().default(""),
  productIds: z.array(z.string()).default([]),
});
export type Collection = z.infer<typeof CollectionSchema>;

export const SocialLinksSchema = z.object({
  tiktok: z.string().nullable().default(null),
  tiktokShop: z.string().nullable().default(null),
  instagram: z.string().nullable().default(null),
  facebook: z.string().nullable().default(null),
  shopee: z.string().nullable().default(null),
  lazada: z.string().nullable().default(null),
  whatsapp: z.string().nullable().default(null).describe("wa.me link or international number"),
  telegram: z.string().nullable().default(null),
  youtube: z.string().nullable().default(null),
  x: z.string().nullable().default(null),
  website: z.string().nullable().default(null),
  email: z.string().nullable().default(null),
});
export type SocialLinks = z.infer<typeof SocialLinksSchema>;

export const BrandSchema = z.object({
  name: z.string(),
  handle: z.string().nullable().default(null).describe("Primary social handle without @"),
  tagline: z.string().default(""),
  description: z.string().default("").describe("2-4 sentence brand summary"),
  story: z.string().default("").describe("Longer about-us text"),
  logo: ImageSchema.nullable().default(null),
  avatar: ImageSchema.nullable().default(null),
  heroImage: ImageSchema.nullable().default(null),
  industry: z.string().default("").describe("e.g. fashion, beauty, food, home, electronics, handmade"),
  audience: z.string().default(""),
  tone: z.string().default("").describe("Voice for copy: e.g. playful, premium, minimal, warm"),
  values: z.array(z.string()).default([]),
  location: z
    .object({
      country: z.string().nullable().default(null),
      city: z.string().nullable().default(null),
    })
    .prefault({}),
  contact: z
    .object({
      email: z.string().nullable().default(null),
      phone: z.string().nullable().default(null),
      whatsapp: z.string().nullable().default(null),
      address: z.string().nullable().default(null),
    })
    .prefault({}),
  followers: z.number().int().nullable().default(null),
});
export type Brand = z.infer<typeof BrandSchema>;

export const ThemeSchema = z.object({
  preset: z
    .string()
    .default("clean")
    .describe("A named look: clean, bold, editorial, playful, luxe, minimal, organic, tech"),
  mode: z.enum(["light", "dark"]).default("light"),
  colors: z
    .object({
      primary: z.string().default("#111111"),
      secondary: z.string().default("#6b7280"),
      accent: z.string().default("#7c3aed"),
      background: z.string().default("#ffffff"),
      surface: z.string().default("#f6f6f7"),
      text: z.string().default("#111111"),
      muted: z.string().default("#6b7280"),
    })
    .prefault({}),
  fonts: z
    .object({
      heading: z.string().default("Inter"),
      body: z.string().default("Inter"),
    })
    .prefault({}),
  radius: z.enum(["none", "sm", "md", "lg", "full"]).default("md"),
});
export type Theme = z.infer<typeof ThemeSchema>;

export const FaqSchema = z.object({ question: z.string(), answer: z.string() });
export const TestimonialSchema = z.object({
  author: z.string(),
  text: z.string(),
  rating: z.number().nullable().default(null),
  source: z.string().nullable().default(null),
});

export const HomeSectionTypeSchema = z.enum([
  "featured",
  "categories",
  "story",
  "testimonials",
  "faq",
  "newsletter",
  "socials",
  "usp",
]);

export const PagesSchema = z.object({
  home: z
    .object({
      heroTitle: z.string().default(""),
      heroSubtitle: z.string().default(""),
      heroCta: z.string().default("Shop now"),
      announcement: z.string().default("").describe("Top bar text, e.g. free shipping"),
      featuredProductIds: z.array(z.string()).default([]),
      sections: z
        .array(
          z.object({
            type: HomeSectionTypeSchema,
            title: z.string().default(""),
            subtitle: z.string().default(""),
          }),
        )
        .default([]),
      usps: z.array(z.object({ title: z.string(), text: z.string() })).default([]),
    })
    .prefault({}),
  about: z
    .object({
      title: z.string().default("About us"),
      body: z.string().default(""),
    })
    .prefault({}),
  faq: z.array(FaqSchema).default([]),
  testimonials: z.array(TestimonialSchema).default([]),
  contact: z
    .object({
      title: z.string().default("Contact"),
      body: z.string().default(""),
    })
    .prefault({}),
});
export type Pages = z.infer<typeof PagesSchema>;

export const CommerceSchema = z.object({
  currency: z.string().default("USD"),
  locale: z.string().default("en"),
  checkout: z
    .object({
      mode: z.enum(["whatsapp", "external_link", "stripe", "none"]).default("whatsapp"),
      whatsappNumber: z.string().nullable().default(null),
      externalUrl: z
        .string()
        .nullable()
        .default(null)
        .describe("Where Buy sends users before native checkout exists (e.g. TikTok Shop / Shopee link)"),
    })
    .prefault({}),
  shipping: z
    .object({
      note: z.string().default(""),
      regions: z.array(z.string()).default([]),
      freeShippingThreshold: z.number().nullable().default(null),
    })
    .prefault({}),
  policies: z
    .object({
      returns: z.string().default(""),
      privacy: z.string().default(""),
      terms: z.string().default(""),
    })
    .prefault({}),
});
export type Commerce = z.infer<typeof CommerceSchema>;

export const SeoSchema = z.object({
  title: z.string().default(""),
  description: z.string().default(""),
  keywords: z.array(z.string()).default([]),
  ogImage: z.string().nullable().default(null),
});

export const SourceKindSchema = z.enum(["profile", "shop", "product", "post", "website", "text"]);
export type SourceKind = z.infer<typeof SourceKindSchema>;

export const SourceRecordSchema = z.object({
  url: z.string(),
  platform: PlatformSchema,
  kind: SourceKindSchema,
  handle: z.string().nullable().default(null),
  fetchedAt: z.string(),
  status: z.enum(["ok", "partial", "blocked", "failed", "skipped"]),
  providers: z.array(z.string()).default([]),
  notes: z.string().default(""),
});
export type SourceRecord = z.infer<typeof SourceRecordSchema>;

export const StoreSpecSchema = z.object({
  version: z.literal(STORE_SPEC_VERSION).default(STORE_SPEC_VERSION),
  id: z.string(),
  slug: z.string(),
  brand: BrandSchema,
  theme: ThemeSchema.prefault({}),
  social: SocialLinksSchema.prefault({}),
  catalog: z
    .object({
      products: z.array(ProductSchema).default([]),
      categories: z.array(CategorySchema).default([]),
      collections: z.array(CollectionSchema).default([]),
    })
    .prefault({}),
  pages: PagesSchema.prefault({}),
  commerce: CommerceSchema.prefault({}),
  seo: SeoSchema.prefault({}),
  template: z
    .object({
      id: z.string().nullable().default(null),
      reason: z.string().default(""),
    })
    .prefault({}),
  sources: z.array(SourceRecordSchema).default([]),
  meta: z
    .object({
      engineVersion: z.string().default("0.1.0"),
      generatedAt: z.string().default(() => new Date().toISOString()),
      updatedAt: z.string().default(() => new Date().toISOString()),
      confidence: z.number().default(0.5),
      warnings: z.array(z.string()).default([]),
    })
    .prefault({}),
});
export type StoreSpec = z.infer<typeof StoreSpecSchema>;

/** Parse + fill defaults. Throws a ZodError with a readable message on failure. */
export function parseStoreSpec(input: unknown): StoreSpec {
  return StoreSpecSchema.parse(input);
}

export function safeParseStoreSpec(input: unknown) {
  return StoreSpecSchema.safeParse(input);
}
